--This file is automatically generated by generate_VHDL_file.m, 15-Mar-2022

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package CONFIG is
	type INPUT is array (natural range <>) of integer range 0 to 255;
	signal connection : INPUT (6 downto 0);
	--connection 2 downto 0 is the input of the neural network
	--connection 6 downto 6 is the output of the neural network

	-- int Arrays with Constants
	type constIntArray is ARRAY (natural range <>) of integer;
	constant networkStructure : constIntArray (2 downto 0) := (1,3,3);
	constant connnectionRange : constIntArray (3 downto 0) := (7,6,3,0);
	constant weights : constIntArray (15 downto 0) := (29152,-220,-231,-243,-51596,368,-327,230,-4197,139,682,-508,9499,-354,-662,226);

	--mapping the 2D network to the 1D Array with the weights
	type KOORDINATES is array (0 to 3, 1 to 2) of natural;
	constant positions: KOORDINATES:=( 
				(0,12),
				(4,16),
				(8,0),
				(12,0));

	-- Ranges for the sum inside a neuron and the multiplication of an input signal with a weight
	constant maxSumRange: integer:=262143;
	constant minSumRange: integer:=-262144;
	constant maxMultRange: integer:=262143;
	constant minMultRange: integer:=-262144;

	-- -- Array for all multiplication results inside a neuron
	type multResults is ARRAY (natural range <>) of integer range minMultRange to maxMultRange;
end CONFIG;
