[Libraries]
work.files = [
	'control.vhd',
	'neuron.vhd',
	'nn_rgb.vhd',
	'sigmoid_IP.vhd',
	'sim_nn_rgb.vhd'
]

[libraries.work]
files = [
	'control.vhd',
	'neuron.vhd',
	'nn_rgb.vhd',
	'sigmoid_IP.vhd',
	'sim_nn_rgb.vhd'
]